CREATE SEQUENCE SEQ_POST;

CREATE TABLE TBL_POST(
   ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
   POST_TITLE VARCHAR2(1000) NOT NULL,
   POST_CONTENT VARCHAR2(1000) NOT NULL,
   POST_REGISTER_DATE DATE DEFAULT SYSDATE,
   POST_UPDATE_DATE DATE DEFAULT SYSDATE,
   MEMBER_NAME VARCHAR2(500)
);

SELECT * FROM TBL_POST;