CREATE SEQUENCE SEQ_ANSWER;

CREATE TABLE ANSWER (
    ID NUMBER CONSTRAINT PK_ANSWER PRIMARY KEY,
    ANSWER_CONTENT VARCHAR2(2000),
    INQUIRE_ID NUMBER NOT NULL,
    CONSTRAINT FK_ANSWER_INQUIRE FOREIGN KEY (INQUIRE_ID)
    REFERENCES INQUIRE_BOARD (ID) ON DELETE CASCADE
);

SELECT * FROM answer;

DROP TABLE ANSWER;

ALTER TABLE ANSWER DROP FOREIGN KEY INQUIRE_ID;