CREATE SEQUENCE SEQ_DORANCOMMENT;

CREATE TABLE DORANCOMMENT (
    ID NUMBER CONSTRAINT PK_DORANCOMMENT PRIMARY KEY,
    CONTENT VARCHAR2(400) NOT NULL,
    REGISTERDATE DATE DEFAULT SYSDATE,
    UPDATEDATE DATE DEFAULT SYSDATE,
    DORANBOARD_ID NUMBER,
    CONSTRAINT FK_DORANCOMMENT_DORANBOARD FOREIGN KEY (DORANBOARD_ID)
    REFERENCES DORANBOARD (ID) ON DELETE CASCADE
);

DROP TABLE DORANCOMMENT ;

ALTER TABLE DORANCOMMENT ADD (USER_ID NUMBER DEFAULT 1);