CREATE SEQUENCE SEQ_FILES;

CREATE TABLE FILES (
    ID NUMBER CONSTRAINT PK_FILES PRIMARY KEY,
    FILE_SIZE NUMBER NOT NULL,
    ORIGIN_NAME VARCHAR2(500),
    UUID NUMBER NOT NULL
    FILE_TYPE VARCHAR2(500)
    FILE_PATH VARCHAR2(1000);
);


 SELECT F.ID, FILE_PATH, F.UUID, F.ORIGIN_NAME, FILE_SIZE, FILE_TYPE, S.ID
        FROM FILES F JOIN SAVINGLEVEL S
        ON F.ID = S.ID AND S.ID = #{id}
        
       SELECT * FROM FILES;
      
      SELECT F.ID, FILE_PATH, F.UUID, F.ORIGIN_NAME, FILE_SIZE, FILE_TYPE
      FROM SAVINGLEVELFILE S JOIN FILES F 
      ON S.ID = F.ID JOIN SAVINGLEVEL L
      		ON S.SAVINGLEVEL_ID = L.ID AND L.ID = #{id}
        SELECT * FROM SAVINGLEVEL;
       

SELECT * FROM SAVINGLEVELFILE;
SELECT * FROM FILES;

        SELECT F.ID, FILE_PATH, F.UUID, F.ORIGIN_NAME, FILE_SIZE, FILE_TYPE
          FROM SAVINGLEVELFILE S JOIN FILES F
          ON S.ID = F.ID JOIN SAVINGLEVEL L
      		    ON S.SAVINGLEVEL_ID = L.ID AND L.ID = 21;

DROP TABLE FILES;

ALTER TABLE FILES MODIFY FILE_TYPE VARCHAR2(500);
ALTER TABLE FILES ADD FILE_TYPE VARCHAR(500);

ALTER TABLE FILES ADD FILE_PATH VARCHAR2(1000);

        SELECT F.ID, FILE_PATH, F.UUID, F.ORIGIN_NAME, FILE_SIZE, FILE_TYPE, SAVINGLEVEL_ID
        FROM FILES F JOIN SAVINGLEVELFILE S
        ON F.ID = S.ID AND SAVINGLEVEL_ID = 21;
        
               SELECT F.ID, FILE_PATH, F.UUID, F.ORIGIN_NAME, FILE_SIZE, FILE_TYPE, SAVINGLEVEL_ID
        FROM FILES F JOIN SAVINGLEVELFILE S
        ON F.ID = S.ID AND SAVINGLEVEL_ID =21;