CREATE SEQUENCE SEQ_INQUIRE;

DELETE SEQUENCE SEQ_INQUIRE;

CREATE TABLE INQUIRE_BOARD (
    ID NUMBER CONSTRAINT PK_INQUIRE PRIMARY KEY,
    INQUIRE_TYPE VARCHAR2(1000) NOT NULL,
    INQUIRE_TITLE VARCHAR2(1000) NOT NULL,
    INQUIRE_CONTENT VARCHAR2(1000),
    INQUIRE_DATE DATE DEFAULT SYSDATE,
    INQUIRE_UPDATE DATE DEFAULT SYSDATE,
    USER_ID NUMBER NOT NULL,
    CONSTRAINT FK_INQUIRE_USERS FOREIGN KEY (USER_ID)
    REFERENCES USERS (ID) ON DELETE CASCADE
);

SELECT * FROM INQUIRE_BOARD;

UPDATE INQUIRE_BOARD
SET STATUS='답변 완료' 
WHERE ID=16;



DROP TABLE INQUIRE_BOARD;

INSERT INTO INQUIRE_BOARD
(ID, INQUIRE_TYPE, INQUIRE_TITLE, INQUIRE_CONTENT, USER_ID, STATUS)
VALUES(SEQ_INQUIRE.NEXTVAL, '문의합니다', '저축 방법이 궁금합니다', '저축은 어떤식으로 할 수 있나요?', 51, '답변대기중');

INSERT INTO INQUIRE_BOARD
(ID, INQUIRE_TYPE, INQUIRE_TITLE, INQUIRE_CONTENT, USER_ID, STATUS)
VALUES(SEQ_INQUIRE.NEXTVAL, '문의합니다', '초보자도 가능한가요?', '제가 저축경험이 없는데 할 수 있나요?', 51, '답변대기중');

INSERT INTO INQUIRE_BOARD
(ID, INQUIRE_TYPE, INQUIRE_TITLE, INQUIRE_CONTENT, USER_ID, STATUS)
VALUES(SEQ_INQUIRE.NEXTVAL, '문의합니다', '저축 단계는 어떻게 되나요?', '저축 단계는 어떻게 되나요?', 51, '답변대기중');

INSERT INTO INQUIRE_BOARD
(ID, INQUIRE_TYPE, INQUIRE_TITLE, INQUIRE_CONTENT, USER_ID, STATUS)
VALUES(SEQ_INQUIRE.NEXTVAL, '문의합니다', '저축인들과 같이 공유할 수 있나요?', '따로 게시판같이 저축 내역을 서로 소통 할 수 있는 공간이 있나요?', 51, '답변대기중');

INSERT INTO INQUIRE_BOARD
(ID, INQUIRE_TYPE, INQUIRE_TITLE, INQUIRE_CONTENT, USER_ID, STATUS)
VALUES(SEQ_INQUIRE.NEXTVAL, '문의합니다', '열매샵은 뭔가요?', '메인 페이지에 열매샵이 있던데 그건 뭔가요?', 51, '답변대기중');

INSERT INTO INQUIRE_BOARD
(ID, INQUIRE_TYPE, INQUIRE_TITLE, INQUIRE_CONTENT, USER_ID, STATUS)
VALUES(SEQ_INQUIRE.NEXTVAL, '문의합니다', '달력은 무슨 기능인가요?', '메인 페이지에 달력이 있던데 어떻게 쓰나요?', 51, '답변대기중');

INSERT INTO INQUIRE_BOARD
(ID, INQUIRE_TYPE, INQUIRE_TITLE, INQUIRE_CONTENT, USER_ID, STATUS)
VALUES(SEQ_INQUIRE.NEXTVAL, '문의합니다', '레벨 단계는 어떻게 구성되어있나요?', '레벨 단계는 어떻게 구성되어있나요?', 51, '답변대기중');

INSERT INTO INQUIRE_BOARD
(ID, INQUIRE_TYPE, INQUIRE_TITLE, INQUIRE_CONTENT, USER_ID, STATUS)
VALUES(SEQ_INQUIRE.NEXTVAL, '문의합니다', '테스트 문의 제목 입니다.', '테스트 내용입니다.', 51, '답변대기중');

INSERT INTO INQUIRE_BOARD
(ID, INQUIRE_TYPE, INQUIRE_TITLE, INQUIRE_CONTENT, USER_ID, STATUS)
VALUES(SEQ_INQUIRE.NEXTVAL, '문의합니다', '테스트 문의 제목 입니다', '레벨 단계는 어떻게 구성되어있나요?', 51, '답변대기중');

INSERT INTO INQUIRE_BOARD
(ID, INQUIRE_TYPE, INQUIRE_TITLE, INQUIRE_CONTENT, USER_ID, STATUS)
VALUES(SEQ_INQUIRE.NEXTVAL, '문의합니다', '테스트 문의 제목 입니다', '레벨 단계는 어떻게 구성되어있나요?', 51, '답변대기중');

INSERT INTO INQUIRE_BOARD
(ID, INQUIRE_TYPE, INQUIRE_TITLE, INQUIRE_CONTENT, USER_ID, STATUS)
VALUES(SEQ_INQUIRE.NEXTVAL, '문의합니다', '테스트 문의 제목 입니다', '레벨 단계는 어떻게 구성되어있나요?', 0, '답변대기중');

