CREATE TABLE ITEMFILE (
    ID NUMBER CONSTRAINT PK_ITEMFILE PRIMARY KEY,
    ITEM_ID NUMBER,
    CONSTRAINT FK_ITEMFILE_FILES FOREIGN KEY (ID)
    REFERENCES FILES (ID),
    CONSTRAINT FK_ITEMFILE_ITEM FOREIGN KEY (ITEM_ID)
    REFERENCES ITEM (ID) ON DELETE CASCADE
);

DROP TABLE ITEMFILE;


SELECT * FROM ITEMFILE ;