CREATE SEQUENCE SEQ_ORDER;


CREATE TABLE ORDERS (
    ID NUMBER CONSTRAINT PK_ORDERS PRIMARY KEY,
    ORDER_AMOUNT NUMBER NOT NULL,
    ORDER_DATE DATE DEFAULT SYSDATE,
    DELIVERY_START_DATE DATE DEFAULT SYSDATE,
    DELIVERY_COMPLETE_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(400) NOT NULL,
    ADDRESS VARCHAR2(400) NOT NULL,
    PAY_STATUS VARCHAR2(400) NOT NULL,
    ITEM_ID NUMBER,
    USER_ID NUMBER,
    CONSTRAINT FK_ORDERS_ITEM FOREIGN KEY (ITEM_ID)
    REFERENCES ITEM (ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORDERS_USERS FOREIGN KEY (USER_ID)
    REFERENCES USERS (ID) ON DELETE CASCADE
);

DROP TABLE ORDERS ;

ALTER TABLE ORDERS ADD ORDER_CANCEL_DATE DATE DEFAULT SYSDATE;

ALTER TABLE ORDERS ADD FINAL_PAY_COUNT NUMBER;