CREATE SEQUENCE SEQ_REVIEW;

CREATE TABLE REVIEW(
	ID NUMBER CONSTRAINT PK_REVIEW PRIMARY KEY,
	CONTENT VARCHAR2(300) NOT NULL,
	SCORE NUMBER NOT NULL,
	REGISTER_DATE DATE DEFAULT SYSDATE NOT NULL,
	ORDER_ID NUMBER,
	CONSTRAINT FK_REVIEW_ORDERS FOREIGN KEY (ORDER_ID)
	REFERENCES ORDERS (ID) ON DELETE CASCADE
);

DROP TABLE REVIEW ;