CREATE SEQUENCE SEQ_SAVINGLEVEL;

CREATE TABLE SAVINGLEVEL (
    ID NUMBER CONSTRAINT PK_SAVINGLEVEL PRIMARY KEY,
    NAME VARCHAR2(500) NOT NULL,
    GOAL_MONEY NUMBER  NOT NULL,
    DAILY_MONEY NUMBER NOT NULL
);

DROP TABLE SAVINGLEVEL;


SELECT * FROM SAVINGLEVEL;

DELETE FROM SAVINGLEVEL
WHERE ID=32;

INSERT INTO SAVINGLEVEL
(ID, NAME, GOAL_MONEY, DAILY_MONEY)
VALUES(SEQ_SAVINGLEVEL.NEXTVAL, '열매', '100000', 1000);

INSERT INTO HR.SAVINGLEVEL
(ID, NAME, GOAL_MONEY, DAILY_MONEY)
VALUES(0, '기본', '0', 0);

ALTER TABLE SAVINGLEVEL MODIFY GOAL_MONEY NUMBER;

        UPDATE SAVINGLEVEL
        SET NAME = '수정' , GOAL_MONEY = 100000 , DAILY_MONEY = 100
        WHERE  ID = 21;
       
         SELECT NAME FROM SAVINGLEVEL
	WHERE NAME = '열매';
