CREATE SEQUENCE SEQ_SAVING;


CREATE TABLE SAVING (
    ID NUMBER CONSTRAINT PK_SAVING PRIMARY KEY,
    START_DATE DATE DEFAULT SYSDATE,
    END_DATE DATE DEFAULT SYSDATE,
    MONEY NUMBER NOT NULL,
    STATUS VARCHAR2(100) NOT NULL,
    USER_ID NUMBER,
    CONSTRAINT FK_SAVING_USERS FOREIGN KEY (USER_ID)
    REFERENCES USERS (ID) ON DELETE CASCADE
);

DROP TABLE SAVING ;
ALTER TABLE SAVING MODIFY START_DATE DATE DEFAULT NULL;
ALTER TABLE SAVING DROP COLUMN END_DATE;