CREATE SEQUENCE SEQ_USER;

CREATE TABLE USERS (
    ID NUMBER CONSTRAINT PK_USERS PRIMARY KEY,
    IDENTIFICATION VARCHAR2(300) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(200) NOT NULL,
    NAME VARCHAR2(200) NOT NULL,
    PHONENUMBER VARCHAR2(200) NOT NULL,
    ADDRESS VARCHAR2(500),
    STATUS VARCHAR2(100) NOT NULL,
    ROLL VARCHAR2(100) NOT NULL,
    CREATEDDATE DATE DEFAULT SYSDATE,
    PROFILEIMAGENAME VARCHAR2(400),
    PROFILEIMAGESIZE NUMBER,
    PROFILEIMAGEUUID NUMBER,
    SAVINGLEVEL_ID NUMBER,
    CONSTRAINT FK_USERS_SAVINGLEVEL FOREIGN KEY (SAVINGLEVEL_ID)
    REFERENCES SAVINGLEVEL (ID) ON DELETE CASCADE
);

ALTER TABLE USERS MODIFY STATUS VARCHAR2(100);

ALTER TABLE USERS ADD ROLL VARCHAR2(100) DEFAULT 'NORMAL' NOT NULL;

ALTER TABLE USERS DROP COLUMN ROLL;

SELECT * FROM USERS ;
TRUNCATE TABLE USERS ;

INSERT INTO USERS
(ID, IDENTIFICATION, PASSWORD, NAME, PHONENUMBER, ADDRESS)
VALUES(SEQ_USER.NEXTVAL, 'test@naver.com15', '123', '허은상', '01034419435', '제주도');

DROP TABLE USERS;

ALTER TABLE USERS DROP COLUMN REGISTERED_NAVER ;
ALTER TABLE USERS DROP COLUMN REGISTERED_KAKAO ;
ALTER TABLE USERS ADD REGISTERED_TYPE VARCHAR2(100) DEFAULT 'NORMAL' NOT NULL;

SELECT COUNT(ID)
FROM USERS;

UPDATE USERS 
SET NAME = '김보령'
WHERE id = 55;

        SELECT NAME, IDENTIFICATION, CREATEDDATE
        FROM USERS 
        ORDER BY CREATEDDATE DESC;

